version: 2.1

defaults: &defaults
  working_directory: ~/intuit/judo
  docker:
    - image: circleci/node:latest-browsers

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package.json checksum
            # when this file is changed, this key will fail
            - intuit/judo-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum ".circleci/config.yml" }}
            - intuit/judo-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - intuit/judo-{{ .Branch }}
            # Find the most recent cache used from any branch
            - intuit/judo-master
            - intuit/judo-
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: intuit/judo-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/intuit/judo
      - run:
          name: Lint
          command: yarn lint

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/intuit/judo
      - run:
          name: Test
          command: yarn test
      - run:
          name: Send CodeCov Results
          command: bash <(curl -s https://codecov.io/bash) -t 0d1ea8b3-0641-4752-91d5-41eabab54f18

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/intuit/judo
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .

  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/intuit/judo
      - run: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Release
          command: yarn run release

workflows:
  version: 2
  build_and_test:
    jobs:
      - install

      - lint:
          requires:
            - install
          filters:
            tags:
              only: /.*/

      - test:
          requires:
            - install
          filters:
            tags:
              only: /.*/

      - build:
          requires:
            - install
          filters:
            tags:
              only: /.*/

      - release:
          requires:
            - lint
            - test
            - build
          filters:
            branches:
              only:
                - master
